updated to last known good state for the ones I've worked on
openshift-instruqt/instruqt pull request #100
Opened 2022-06-06 15:49 UTC by reselbob

These are the Instruqt's I've updated:

https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/getting-started
https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/cluster-access/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-on-openshift/developing-with-odo
https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/deploying-images/
https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/deploying-python/
https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/resource-objects/
https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/port-forwarding/
https://github.com/openshift-instruqt/instruqt/blob/master/using-the-cluster/transferring-files/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/getting-started/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/spring/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/kafka/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/panache/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/qute/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/monitoring/
https://github.com/openshift-instruqt/instruqt/blob/master/developing-with-quarkus/reactive-sql/

2022-06-07 16:32 UTC, ryanj requested changes
It looks like two of the tracks are now located in the root of the repo (one on quarkus, another on tranferring files to/from PVCs).  Those two need to be moved into an appropriate subfolder

I'm seeing a lot of deletions for PNGs inside the `assets` folder. It seems like there are more deletions than additions.  Is this expected?  Are we sure we are not losing PNGs in the process?

2022-06-07 17:14 UTC, reselbob commented
@ryanj The deleted pngs are to be expected in that I created and deleted graphic files as a matter of construction. Let me take a look at the directories in the root. I am wonder if I made a copy and paste error.

2022-06-07 19:51 UTC, ryanj commented
@blues-man Looks like this PR will revert some of your `4-10` updates
Is this alright with you?  

Bob and I had discussed the following rollout plan:

1. @blues-man to review this PR; approve changes / regressions in `track.yml`, `config.yml`, and `track-scripts/setup-crc` files
2. Merge the PR if it passes review
3. Select two tracks for testing: the `getting-started/cluster access` track, and `developing-on-openshift/developing-with-odo` track
4. Run `instruqt track push` (with the 4-9 settings) on these two tracks to verify that content updates have landed in the repo.  
  * QA expectation: no change. if the content has been working on 4-9 then it should continue working on 4-9 after the merge.
5. Create a new PR that will update the `cluster access` track, and the `developing-with-odo` track to OpenShift 4-10
6. Run `instruqt track push` with the 4-10 updates.  Confirm that the `cluster access` track, and the `developing-with-odo` track work with OpenShift 4-10.
  * QA expectation: `oc version` should show that we're running on openshift-4-10. Make sure the content still works correctly using the new openshift backend.
7. If the openshift 4-10 updates work well on the `cluster access` track, and the `developing-with-odo` track, then merge the PR that was created in step 5.
8. Regroup the following day to repeat steps 3-7 with the next few tracks from Bob's list of updated content.  Schedule additional meetings until we have successfully validated the each of the 4-10 updates in production

2022-06-08 16:53 UTC, ryanj approved these changes

2022-06-08 16:54 UTC, merged